import { db } from './index.js';
import { leads } from './schema.js';

async function seedLeads() {
    try {
        console.log('Seeding leads table with dummy data...');

        const dummyLeads = [
            {
                first_name: 'Robert',
                last_name: 'Johnson',
                middle_initial: 'M',
                date_of_birth: '1965-03-15',
                phone: '(555) 123-4567',
                email: 'robert.johnson@email.com',
                address: '123 Main Street, Apt 4B',
                state_of_birth: 'California',
                ssn: '123-45-6789',
                height: '5\'10"',
                weight: '180 lbs',
                insurance_provider: 'Blue Cross',
                policy_number: 'BC123456',
                medical_notes: 'No known allergies',
                doctor_name: 'Dr. Sarah Smith',
                doctor_phone: '(555) 987-6543',
                doctor_address: '456 Medical Plaza',
                beneficiary_details: 'Mary Johnson (Spouse) - 100%',
                plan_details: 'PPO Plan - $500 deductible',
                health_q1: false,
                health_q2: false,
                health_q3: false,
                health_q4: false,
                health_q5: false,
                health_q6: false,
                health_q7a: false,
                health_q7b: false,
                health_q7c: false,
                health_q7d: false,
                health_q8a: false,
                health_q8b: false,
                health_q8c: false,
                covid_question: false,
                bank_name: 'Chase Bank',
                account_name: 'Robert M Johnson',
                account_number: '1234567890',
                routing_number: '021000021',
                account_type: 'checking',
                banking_comments: null,
                status: 'Entry',
                assigned_to: 1,
            },
            {
                first_name: 'Maria',
                last_name: 'Garcia',
                middle_initial: 'L',
                date_of_birth: '1972-07-22',
                phone: '(555) 234-5678',
                email: 'maria.garcia@email.com',
                address: '789 Oak Avenue',
                state_of_birth: 'Texas',
                ssn: '234-56-7890',
                height: '5\'6"',
                weight: '145 lbs',
                insurance_provider: 'Aetna',
                policy_number: 'AE789012',
                medical_notes: 'Diabetic - Type 2',
                doctor_name: 'Dr. Michael Chen',
                doctor_phone: '(555) 876-5432',
                doctor_address: '789 Health Center Blvd',
                beneficiary_details: 'Carlos Garcia (Son) - 50%, Ana Garcia (Daughter) - 50%',
                plan_details: 'HMO Plan - $1000 deductible',
                health_q1: false,
                health_q2: false,
                health_q3: false,
                health_q4: true,
                health_q5: false,
                health_q6: false,
                health_q7a: false,
                health_q7b: false,
                health_q7c: false,
                health_q7d: false,
                health_q8a: false,
                health_q8b: false,
                health_q8c: false,
                covid_question: false,
                bank_name: 'Bank of America',
                account_name: 'Maria L Garcia',
                account_number: '2345678901',
                routing_number: '026009593',
                account_type: 'saving',
                banking_comments: null,
                status: 'Manager Review',
                assigned_to: 2,
            },
            {
                first_name: 'James',
                last_name: 'Williams',
                middle_initial: 'A',
                date_of_birth: '1958-11-30',
                phone: '(555) 345-6789',
                email: 'james.williams@email.com',
                address: '321 Pine Street',
                state_of_birth: 'Florida',
                ssn: '345-67-8901',
                height: '6\'0"',
                weight: '195 lbs',
                insurance_provider: 'United Healthcare',
                policy_number: 'UH345678',
                medical_notes: 'High blood pressure, controlled with medication',
                doctor_name: 'Dr. Jennifer Lee',
                doctor_phone: '(555) 765-4321',
                doctor_address: '234 Wellness Drive',
                beneficiary_details: 'Patricia Williams (Spouse) - 100%',
                plan_details: 'EPO Plan - $750 deductible',
                health_q1: false,
                health_q2: false,
                health_q3: false,
                health_q4: false,
                health_q5: false,
                health_q6: false,
                health_q7a: false,
                health_q7b: false,
                health_q7c: false,
                health_q7d: false,
                health_q8a: false,
                health_q8b: false,
                health_q8c: false,
                covid_question: false,
                bank_name: 'Wells Fargo',
                account_name: 'James A Williams',
                account_number: '3456789012',
                routing_number: '121000248',
                account_type: 'checking',
                banking_comments: null,
                status: 'QA Review',
                assigned_to: 3,
            },
            {
                first_name: 'Linda',
                last_name: 'Brown',
                middle_initial: 'K',
                date_of_birth: '1970-05-18',
                phone: '(555) 456-7890',
                email: 'linda.brown@email.com',
                address: '567 Elm Road',
                state_of_birth: 'New York',
                ssn: '456-78-9012',
                height: '5\'5"',
                weight: '135 lbs',
                insurance_provider: 'Cigna',
                policy_number: 'CG456789',
                medical_notes: 'No significant medical history',
                doctor_name: 'Dr. Robert Taylor',
                doctor_phone: '(555) 654-3210',
                doctor_address: '890 Care Center',
                beneficiary_details: 'Michael Brown (Husband) - 100%',
                plan_details: 'PPO Plan - $500 deductible',
                health_q1: false,
                health_q2: false,
                health_q3: false,
                health_q4: false,
                health_q5: false,
                health_q6: false,
                health_q7a: false,
                health_q7b: false,
                health_q7c: false,
                health_q7d: false,
                health_q8a: false,
                health_q8b: false,
                health_q8c: false,
                covid_question: false,
                bank_name: 'Citibank',
                account_name: 'Linda K Brown',
                account_number: '4567890123',
                routing_number: '021000089',
                account_type: 'checking',
                banking_comments: null,
                status: 'Approved',
                assigned_to: 1,
            },
            {
                first_name: 'David',
                last_name: 'Martinez',
                middle_initial: 'R',
                date_of_birth: '1963-09-25',
                phone: '(555) 567-8901',
                email: 'david.martinez@email.com',
                address: '890 Maple Lane',
                state_of_birth: 'Arizona',
                ssn: '567-89-0123',
                height: '5\'11"',
                weight: '190 lbs',
                insurance_provider: 'Humana',
                policy_number: 'HU567890',
                medical_notes: 'Asthma - uses inhaler',
                doctor_name: 'Dr. Emily Davis',
                doctor_phone: '(555) 543-2109',
                doctor_address: '123 Medical Tower',
                beneficiary_details: 'Susan Martinez (Spouse) - 50%, David Jr (Son) - 50%',
                plan_details: 'HMO Plan - $1200 deductible',
                health_q1: false,
                health_q2: false,
                health_q3: false,
                health_q4: false,
                health_q5: false,
                health_q6: false,
                health_q7a: false,
                health_q7b: false,
                health_q7c: false,
                health_q7d: false,
                health_q8a: false,
                health_q8b: false,
                health_q8c: false,
                covid_question: false,
                bank_name: 'TD Bank',
                account_name: 'David R Martinez',
                account_number: '5678901234',
                routing_number: '031101266',
                account_type: 'checking',
                banking_comments: null,
                status: 'Pending',
                assigned_to: 2,
            },
        ];

        for (const lead of dummyLeads) {
            await db.insert(leads).values(lead);
        }

        console.log(`✅ Successfully seeded ${dummyLeads.length} leads!`);
        process.exit(0);
    } catch (error) {
        console.error('Error seeding leads:', error);
        process.exit(1);
    }
}

seedLeads();
